import PDFDocument from "pdfkit";
import { prisma } from "../prisma";
import { canAccessResults, ResultsError } from "./assessmentResults";
import { hasPermission, PERMISSIONS, UserAccessContext } from "./permissions";
import {
  CONCESSION_TYPE_LABELS,
  getAssessmentConcessionAlerts,
} from "./concessions";

const GOLD = "#d4af37";
const DARK = "#1a1a1a";
const MUTED = "#666666";

function formatDate(value: Date | string | null | undefined): string {
  if (!value) return "—";
  const d = typeof value === "string" ? new Date(value) : value;
  return d.toLocaleDateString("en-ZA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function csvEscape(value: string | number | null | undefined): string {
  if (value == null) return "";
  const str = String(value);
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function pdfBuffer(build: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    build(doc);
    doc.end();
  });
}

async function loadReportData(
  assessmentId: string,
  workspaceId: string,
  access: UserAccessContext
) {
  if (!hasPermission(access, workspaceId, PERMISSIONS.REPORTS_GENERATE)) {
    throw new ResultsError("You do not have permission to generate reports", 403);
  }

  const assessment = await prisma.assessment.findFirst({
    where: { id: assessmentId, workspaceId },
    include: {
      subject: { select: { name: true } },
      grade: { select: { name: true } },
    },
  });

  if (!assessment) throw new ResultsError("Assessment not found", 404);
  if (!canAccessResults(access, workspaceId, assessment.creatorTeacherId)) {
    throw new ResultsError("You do not have permission to view this assessment", 403);
  }

  const alerts = await getAssessmentConcessionAlerts(assessmentId, workspaceId);

  return { assessment, alerts };
}

export async function generateExamPrepPdf(
  assessmentId: string,
  workspaceId: string,
  access: UserAccessContext
): Promise<Buffer> {
  const { assessment, alerts } = await loadReportData(
    assessmentId,
    workspaceId,
    access
  );

  return pdfBuffer((doc) => {
    doc.rect(0, 0, doc.page.width, 72).fill(DARK);
    doc.fillColor(GOLD).fontSize(20).font("Helvetica-Bold");
    doc.text("ScriptCheck", 50, 28);
    doc.fillColor("#ffffff").fontSize(11).font("Helvetica");
    doc.text("Exam Preparation Report — Concessions", 50, 52);
    doc.fillColor("#000000");
    doc.y = 90;

    doc.fontSize(10).font("Helvetica");
    doc.text(`Assessment: ${assessment.title}`);
    doc.text(`Subject: ${assessment.subject.name}`);
    doc.text(`Grade: ${assessment.grade.name}`);
    doc.text(`Date: ${formatDate(assessment.assessmentDate)}`);
    doc.moveDown();

    if (alerts.length === 0) {
      doc.text("No learners with active concessions for this assessment.");
      return;
    }

    doc.font("Helvetica-Bold").text("Learners with concessions", { underline: true });
    doc.moveDown(0.5);
    doc.font("Helvetica");

    for (const alert of alerts) {
      if (doc.y > doc.page.height - 100) doc.addPage();
      doc.font("Helvetica-Bold").text(`⚠ ${alert.fullName} (${alert.learnerNumber})`);
      doc.font("Helvetica");
      if (alert.className) doc.text(`Class: ${alert.className}`);
      doc.text(`Concessions: ${alert.summary}`);
      for (const c of alert.concessions) {
        const req = c.description
          ? `${c.label} — ${c.description}`
          : c.label;
        doc.text(`  • ${req}`);
      }
      doc.moveDown();
    }

    const bottom = doc.page.height - 40;
    doc
      .fillColor(MUTED)
      .fontSize(8)
      .text("Generated by ScriptCheck", 50, bottom, {
        align: "center",
        width: doc.page.width - 100,
      });
  });
}

export async function generateExamPrepCsv(
  assessmentId: string,
  workspaceId: string,
  access: UserAccessContext
): Promise<string> {
  const { assessment, alerts } = await loadReportData(
    assessmentId,
    workspaceId,
    access
  );

  const lines: string[] = [
    [
      "Assessment",
      "Subject",
      "Grade",
      "Date",
      "Learner Number",
      "Learner",
      "Class",
      "Concession",
      "Requirements",
    ].join(","),
  ];

  for (const alert of alerts) {
    for (const c of alert.concessions) {
      lines.push(
        [
          csvEscape(assessment.title),
          csvEscape(assessment.subject.name),
          csvEscape(assessment.grade.name),
          csvEscape(formatDate(assessment.assessmentDate)),
          csvEscape(alert.learnerNumber),
          csvEscape(alert.fullName),
          csvEscape(alert.className),
          csvEscape(c.label),
          csvEscape(c.description ?? c.label),
        ].join(",")
      );
    }
  }

  return lines.join("\n");
}

export { CONCESSION_TYPE_LABELS };
