import PDFDocument from "pdfkit";
import { AssessmentStatus } from "@prisma/client";
import { prisma } from "../prisma";
import { drawPdfHeader, PDF_GOLD, PDF_MUTED } from "./pdfHelpers";
import {
  canAccessResults,
  getAssessmentResults,
  hasBroadResultsAccess,
  parseAnalyticsSnapshot,
  ResultsError,
} from "./assessmentResults";
import { hasPermission, PERMISSIONS, UserAccessContext } from "./permissions";

function formatDate(value: Date | string | null | undefined): string {
  if (!value) return "—";
  const d = typeof value === "string" ? new Date(value) : value;
  return d.toLocaleDateString("en-ZA", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function formatPct(value: number | null | undefined): string {
  if (value == null) return "—";
  return `${value}%`;
}

function pdfBuffer(build: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    build(doc);
    doc.end();
  });
}

function drawFooter(doc: PDFKit.PDFDocument) {
  const bottom = doc.page.height - 40;
  doc
    .strokeColor(PDF_GOLD)
    .lineWidth(0.5)
    .moveTo(50, bottom - 8)
    .lineTo(doc.page.width - 50, bottom - 8)
    .stroke();
  doc
    .fillColor(PDF_MUTED)
    .fontSize(8)
    .font("Helvetica")
    .text("Generated by ScriptCheck", 50, bottom, {
      align: "center",
      width: doc.page.width - 100,
    });
}

function drawLabelValue(
  doc: PDFKit.PDFDocument,
  label: string,
  value: string,
  x: number,
  y: number,
  width: number
) {
  doc.fillColor(PDF_MUTED).fontSize(8).font("Helvetica").text(label, x, y, { width });
  doc.fillColor("#000000").fontSize(10).font("Helvetica-Bold").text(value, x, y + 12, { width });
}

export function canGenerateReports(
  access: UserAccessContext,
  workspaceId: string,
  creatorTeacherId: string
): boolean {
  if (!hasPermission(access, workspaceId, PERMISSIONS.REPORTS_GENERATE)) {
    return false;
  }
  if (hasBroadResultsAccess(access, workspaceId)) return true;
  return creatorTeacherId === access.userId;
}

async function loadAssessmentReportContext(assessmentId: string, workspaceId: string) {
  const assessment = await prisma.assessment.findFirst({
    where: { id: assessmentId, workspaceId },
    include: {
      workspace: { select: { name: true } },
      curriculum: { select: { code: true, name: true } },
      phase: { select: { name: true } },
      grade: { select: { name: true } },
      subject: { select: { name: true } },
      creatorTeacher: { select: { fullName: true } },
    },
  });

  if (!assessment) throw new ResultsError("Assessment not found", 404);

  const publishAudit = await prisma.auditLog.findFirst({
    where: {
      workspaceId,
      action: "RESULTS_PUBLISHED",
      metadata: {
        path: ["assessmentId"],
        equals: assessmentId,
      },
    },
    orderBy: { createdAt: "desc" },
    include: { actor: { select: { fullName: true } } },
  });

  const hodName =
    publishAudit?.actor?.fullName ??
    (
      await prisma.workspaceMembership.findFirst({
        where: {
          workspaceId,
          isActive: true,
          roles: { some: { role: "HOD" } },
        },
        include: { user: { select: { fullName: true } } },
      })
    )?.user.fullName ??
    "—";

  return { assessment, hodName };
}

export async function generateAssessmentSummaryPdf(
  assessmentId: string,
  workspaceId: string,
  access: UserAccessContext
): Promise<Buffer> {
  const { assessment, hodName } = await loadAssessmentReportContext(assessmentId, workspaceId);

  if (!canGenerateReports(access, workspaceId, assessment.creatorTeacherId)) {
    throw new ResultsError("You do not have permission to generate this report", 403);
  }

  const results = await getAssessmentResults(assessmentId, workspaceId, access);
  const snapshot = parseAnalyticsSnapshot(assessment.analyticsSnapshot);
  const summary = snapshot ?? results.summary;
  const questionRows = snapshot?.questionAnalysisSummary ?? results.questionAnalysis;
  const weakTopics = snapshot?.weakTopics ?? results.weakTopics;

  return pdfBuffer((doc) => {
    drawPdfHeader(
      doc,
      "Assessment Summary Report",
      assessment.title
    );

    const colW = (doc.page.width - 100) / 2;
    let y = doc.y;

    drawLabelValue(doc, "School / Workspace", assessment.workspace.name, 50, y, colW);
    drawLabelValue(doc, "Assessment", assessment.title, 50 + colW, y, colW);
    y += 36;
    drawLabelValue(
      doc,
      "Curriculum",
      `${assessment.curriculum.code} — ${assessment.curriculum.name}`,
      50,
      y,
      colW
    );
    drawLabelValue(doc, "Phase", assessment.phase.name, 50 + colW, y, colW);
    y += 36;
    drawLabelValue(doc, "Grade", assessment.grade.name, 50, y, colW);
    drawLabelValue(doc, "Subject", assessment.subject.name, 50 + colW, y, colW);
    y += 36;
    drawLabelValue(doc, "Teacher", assessment.creatorTeacher.fullName, 50, y, colW);
    drawLabelValue(doc, "HOD", hodName, 50 + colW, y, colW);
    y += 36;
    drawLabelValue(
      doc,
      "Date Published",
      formatDate(assessment.publishedAt),
      50,
      y,
      colW
    );
    drawLabelValue(
      doc,
      "Status",
      assessment.status,
      50 + colW,
      y,
      colW
    );

    doc.y = y + 50;
    doc.fillColor(PDF_GOLD).fontSize(12).font("Helvetica-Bold").text("Analytics Summary");
    doc.moveDown(0.5);

    const stats = [
      ["Class Average", formatPct("classAverage" in summary ? summary.classAverage : results.summary.classAverage)],
      ["Pass Rate", formatPct("passRate" in summary ? summary.passRate : results.summary.passRate)],
      [
        "Highest Mark",
        String(
          "highestMark" in summary && summary.highestMark != null
            ? summary.highestMark
            : results.summary.highestMark ?? "—"
        ),
      ],
      [
        "Lowest Mark",
        String(
          "lowestMark" in summary && summary.lowestMark != null
            ? summary.lowestMark
            : results.summary.lowestMark ?? "—"
        ),
      ],
      [
        "Learner Count",
        String(
          "learnerCount" in summary
            ? summary.learnerCount
            : results.summary.totalLearners
        ),
      ],
    ];

    let statY = doc.y;
    for (let i = 0; i < stats.length; i++) {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = 50 + col * 170;
      const sy = statY + row * 32;
      doc.fillColor(PDF_MUTED).fontSize(8).text(stats[i][0], x, sy);
      doc.fillColor("#000000").fontSize(11).font("Helvetica-Bold").text(stats[i][1], x, sy + 11);
    }
    doc.y = statY + 80;

    doc.fillColor(PDF_GOLD).fontSize(12).font("Helvetica-Bold").text("Question Analysis");
    doc.moveDown(0.3);

    const qHeaders = ["Q", "Avg %", "Topic", "Difficulty", "Cognitive"];
    const colWidths = [30, 50, 140, 80, 100];
    let tableY = doc.y;
    let x = 50;
    doc.fontSize(8).font("Helvetica-Bold").fillColor(PDF_MUTED);
    for (let i = 0; i < qHeaders.length; i++) {
      doc.text(qHeaders[i], x, tableY, { width: colWidths[i] });
      x += colWidths[i];
    }
    tableY += 14;
    doc.font("Helvetica").fillColor("#000000").fontSize(8);

    for (const q of questionRows) {
      if (tableY > doc.page.height - 80) {
        doc.addPage();
        tableY = 50;
      }
      x = 50;
      const row = [
        q.questionNumber,
        formatPct(q.averagePercentage),
        q.topic || "—",
        q.difficulty || "—",
        q.cognitiveLevel || "—",
      ];
      for (let i = 0; i < row.length; i++) {
        doc.text(row[i], x, tableY, { width: colWidths[i] });
        x += colWidths[i];
      }
      tableY += 14;
    }

    doc.y = tableY + 16;
    if (weakTopics.length > 0) {
      doc.fillColor(PDF_GOLD).fontSize(12).font("Helvetica-Bold").text("Weak Topics");
      doc.moveDown(0.3);
      doc.fontSize(9).font("Helvetica").fillColor("#000000");
      for (const topic of weakTopics.slice(0, 12)) {
        doc.text(
          `• ${topic.topic}: ${formatPct(topic.averagePercentage)} avg (${topic.learnersStruggling ?? 0} learners struggling)`,
          50,
          doc.y,
          { width: doc.page.width - 100 }
        );
        doc.moveDown(0.2);
      }
    }

    drawFooter(doc);
  });
}

export async function generateLearnerResultPdf(
  scriptId: string,
  workspaceId: string,
  access: UserAccessContext
): Promise<Buffer> {
  const script = await prisma.learnerScript.findFirst({
    where: { id: scriptId, batch: { workspaceId } },
    include: {
      learner: { include: { grade: { select: { name: true } } } },
      assessment: {
        include: {
          workspace: { select: { name: true } },
          curriculum: { select: { code: true, name: true } },
          phase: { select: { name: true } },
          grade: { select: { name: true } },
          subject: { select: { name: true } },
          creatorTeacher: { select: { id: true, fullName: true } },
        },
      },
      questionMarks: {
        orderBy: { questionNumber: "asc" },
        include: {
          assessmentQuestion: { select: { questionText: true } },
        },
      },
      feedback: {
        orderBy: { createdAt: "desc" },
        take: 5,
        include: { createdBy: { select: { fullName: true } } },
      },
    },
  });

  if (!script) throw new ResultsError("Learner script not found", 404);

  if (
    !canGenerateReports(
      access,
      workspaceId,
      script.assessment.creatorTeacherId
    )
  ) {
    throw new ResultsError("You do not have permission to generate this report", 403);
  }

  const totalMarks = script.assessment.totalMarks;
  const finalTotal = script.finalTotal ?? 0;
  const percentage =
    totalMarks > 0 ? Math.round((finalTotal / totalMarks) * 1000) / 10 : 0;

  const teacherComment =
    script.feedback.find((f) => f.teacherFeedback)?.teacherFeedback ||
    script.questionMarks
      .map((m) => m.teacherComment)
      .filter(Boolean)
      .join("; ") ||
    "—";

  const hodComment =
    script.feedback.find((f) => f.hodFeedback)?.hodFeedback ||
    script.questionMarks
      .map((m) => m.hodComment)
      .filter(Boolean)
      .join("; ") ||
    "—";

  return pdfBuffer((doc) => {
    drawPdfHeader(doc, "Learner Result Report", script.assessment.title);

    const colW = (doc.page.width - 100) / 2;
    let y = doc.y;

    drawLabelValue(doc, "Learner Number", script.learner.learnerNumber, 50, y, colW);
    drawLabelValue(
      doc,
      "Learner Name",
      `${script.learner.firstName} ${script.learner.lastName}`.trim(),
      50 + colW,
      y,
      colW
    );
    y += 36;
    drawLabelValue(doc, "Grade", script.learner.grade.name, 50, y, colW);
    drawLabelValue(doc, "Class", script.learner.className || "—", 50 + colW, y, colW);
    y += 36;
    drawLabelValue(doc, "School", script.assessment.workspace.name, 50, y, colW);
    drawLabelValue(doc, "Subject", script.assessment.subject.name, 50 + colW, y, colW);
    y += 36;
    drawLabelValue(doc, "Assessment", script.assessment.title, 50, y, colW);
    drawLabelValue(doc, "Teacher", script.assessment.creatorTeacher.fullName, 50 + colW, y, colW);

    doc.y = y + 44;
    doc.fillColor(PDF_GOLD).fontSize(12).font("Helvetica-Bold").text("Question Breakdown");
    doc.moveDown(0.3);

    const headers = ["Question", "Obtained", "Max"];
    const widths = [300, 80, 80];
    let tableY = doc.y;
    let x = 50;
    doc.fontSize(8).font("Helvetica-Bold").fillColor(PDF_MUTED);
    for (let i = 0; i < headers.length; i++) {
      doc.text(headers[i], x, tableY, { width: widths[i] });
      x += widths[i];
    }
    tableY += 14;
    doc.font("Helvetica").fillColor("#000000");

    for (const mark of script.questionMarks) {
      if (tableY > doc.page.height - 120) {
        doc.addPage();
        tableY = 50;
      }
      x = 50;
      const qLabel = `Q${mark.questionNumber}`;
      const obtained = mark.finalMark != null ? String(mark.finalMark) : "—";
      doc.fontSize(8).text(qLabel, x, tableY, { width: widths[0] });
      doc.text(obtained, x + widths[0], tableY, { width: widths[1] });
      doc.text(String(mark.maxMarks), x + widths[0] + widths[1], tableY, { width: widths[2] });
      tableY += 14;
    }

    doc.y = tableY + 20;
    doc.fillColor(PDF_GOLD).fontSize(12).font("Helvetica-Bold").text("Totals");
    doc.moveDown(0.4);
    drawLabelValue(doc, "Final Mark", `${finalTotal} / ${totalMarks}`, 50, doc.y, 200);
    drawLabelValue(doc, "Percentage", `${percentage}%`, 260, doc.y, 200);
    drawLabelValue(doc, "Status", script.status, 50, doc.y + 36, 200);

    doc.y += 80;
    doc.fillColor("#000000").fontSize(10).font("Helvetica-Bold").text("Teacher Comment");
    doc.font("Helvetica").fontSize(9).text(teacherComment, 50, doc.y + 4, {
      width: doc.page.width - 100,
    });
    doc.moveDown(0.8);
    doc.font("Helvetica-Bold").fontSize(10).text("HOD Comment");
    doc.font("Helvetica").fontSize(9).text(hodComment, 50, doc.y + 4, {
      width: doc.page.width - 100,
    });

    drawFooter(doc);
  });
}

export async function assertReportableAssessment(
  assessmentId: string,
  workspaceId: string
) {
  const assessment = await prisma.assessment.findFirst({
    where: { id: assessmentId, workspaceId },
    select: { status: true },
  });
  if (!assessment) throw new ResultsError("Assessment not found", 404);
  if (
    assessment.status !== AssessmentStatus.PUBLISHED &&
    assessment.status !== AssessmentStatus.MARKED &&
    assessment.status !== AssessmentStatus.HOD_REVIEW &&
    assessment.status !== AssessmentStatus.APPROVED
  ) {
    throw new ResultsError("Reports are available after marking is complete", 400);
  }
}
