import PDFDocument from "pdfkit";
import { prisma } from "../prisma";
import {
  getPortalAnalytics,
  getPortalAtRisk,
  getPortalLearnerDashboard,
  getPortalLearnerHistory,
} from "./portalData";

const GOLD = "#d4af37";
const DARK = "#1a1a1a";
const MUTED = "#666666";

function pdfBuffer(build: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    build(doc);
    doc.end();
  });
}

function formatPct(value: number | null | undefined): string {
  if (value == null) return "—";
  return `${value}%`;
}

export async function generatePortalProgressPdf(
  workspaceId: string,
  learnerId: string
): Promise<Buffer> {
  const workspace = await prisma.workspace.findUnique({
    where: { id: workspaceId },
    select: { name: true },
  });

  const [dashboard, history, analytics, atRisk] = await Promise.all([
    getPortalLearnerDashboard(workspaceId, learnerId),
    getPortalLearnerHistory(workspaceId, learnerId),
    getPortalAnalytics(workspaceId, learnerId),
    getPortalAtRisk(workspaceId, learnerId),
  ]);

  return pdfBuffer((doc) => {
    doc.rect(0, 0, doc.page.width, 72).fill(DARK);
    doc.fillColor(GOLD).fontSize(20).font("Helvetica-Bold");
    doc.text("ScriptCheck", 50, 28);
    doc.fillColor("#ffffff").fontSize(11).font("Helvetica");
    doc.text("Learner Academic Progress Report", 50, 52);
    doc.fillColor("#000000");
    doc.y = 90;

    doc.fontSize(10).font("Helvetica-Bold");
    doc.text("Learner Details", { underline: true });
    doc.font("Helvetica");
    doc.text(`Name: ${dashboard.learner.fullName}`);
    doc.text(`Learner Number: ${dashboard.learner.learnerNumber}`);
    doc.text(`Grade: ${dashboard.learner.grade.name}`);
    if (dashboard.learner.className) doc.text(`Class: ${dashboard.learner.className}`);
    doc.text(`School: ${workspace?.name ?? "—"}`);
    doc.moveDown();

    doc.font("Helvetica-Bold").text("Summary", { underline: true });
    doc.font("Helvetica");
    doc.text(`Academic Average: ${formatPct(dashboard.cards.academicAverage)}`);
    doc.text(`Assessments Completed: ${dashboard.cards.assessmentsCompleted}`);
    doc.text(`Distinctions: ${dashboard.cards.distinctions}`);
    doc.text(`Subjects At Risk: ${dashboard.cards.subjectsAtRisk}`);
    doc.moveDown();

    if (dashboard.subjectAverages.length > 0) {
      doc.font("Helvetica-Bold").text("Subject Averages", { underline: true });
      doc.font("Helvetica");
      for (const s of dashboard.subjectAverages) {
        doc.text(`${s.subject}: ${formatPct(s.average)} (${s.assessmentCount} assessments)`);
      }
      doc.moveDown();
    }

    if (history.timeline.length > 0) {
      doc.font("Helvetica-Bold").text("Assessment Summary", { underline: true });
      doc.font("Helvetica");
      for (const a of history.timeline.slice(-15)) {
        doc.text(
          `${a.title} (${a.subject}) — ${a.mark ?? "—"}/${a.totalMarks} (${formatPct(a.percentage)})`
        );
      }
      doc.moveDown();
    }

    if (analytics.performanceGrowth != null) {
      doc.font("Helvetica-Bold").text("Performance Trend", { underline: true });
      doc.font("Helvetica");
      doc.text(
        `Overall growth: ${analytics.performanceGrowth > 0 ? "+" : ""}${analytics.performanceGrowth}%`
      );
      if (analytics.gradeComparison.gradeAverage != null) {
        doc.text(
          `Grade average: ${formatPct(analytics.gradeComparison.gradeAverage)} · Learner: ${formatPct(analytics.gradeComparison.learnerAverage)}`
        );
      }
      doc.moveDown();
    }

    if (atRisk.active) {
      doc.font("Helvetica-Bold").fillColor("#cc6600").text("At-Risk Indicators", { underline: true });
      doc.fillColor("#000000").font("Helvetica");
      for (const alert of atRisk.alerts) {
        doc.text(`• ${alert.label}`);
      }
      if (atRisk.guidance) {
        doc.moveDown(0.3);
        doc.text(atRisk.guidance);
      }
      doc.moveDown();
    }

    const bottom = doc.page.height - 40;
    doc
      .fillColor(MUTED)
      .fontSize(8)
      .text("Generated by ScriptCheck · Read-only portal report", 50, bottom, {
        align: "center",
        width: doc.page.width - 100,
      });
  });
}

export async function countPortalLoginsSince(
  workspaceId: string,
  since: Date
): Promise<number> {
  return prisma.auditLog.count({
    where: {
      workspaceId,
      action: "PORTAL_LOGIN",
      createdAt: { gte: since },
    },
  });
}

export async function countPortalReportDownloads(
  workspaceId: string,
  since?: Date
): Promise<number> {
  return prisma.auditLog.count({
    where: {
      workspaceId,
      action: "PORTAL_REPORT_DOWNLOADED",
      ...(since ? { createdAt: { gte: since } } : {}),
    },
  });
}

export async function getRecentPortalActivity(workspaceId: string, limit = 10) {
  const logs = await prisma.auditLog.findMany({
    where: {
      workspaceId,
      action: {
        in: ["PORTAL_LOGIN", "PORTAL_REPORT_DOWNLOADED", "PORTAL_ACCESS_DENIED"],
      },
    },
    orderBy: { createdAt: "desc" },
    take: limit,
  });

  return logs.map((log) => ({
    id: log.id,
    action: log.action,
    metadata: log.metadata as Record<string, unknown> | null,
    createdAt: log.createdAt.toISOString(),
  }));
}

export async function countAtRiskPortalViews(workspaceId: string): Promise<number> {
  return prisma.auditLog.count({
    where: {
      workspaceId,
      action: "PORTAL_LOGIN",
      metadata: { path: ["portalType"], equals: "LEARNER" },
    },
  });
}
